sudo: false

addons:
  apt:
    packages:
    - bc

cache:
  directories:
    - $HOME/.buildroot-dl
    - $HOME/.buildroot-ccache

script:
    - mkdir -p $HOME/.buildroot-dl
    - ln -s $HOME/.buildroot-dl buildroot/dl
    - make FORCE_CCACHE=1 -s
