sudo: false

addons:
  apt:
    packages:
    - bc

env:
  global:
    - GZIP: --rsyncable

cache:
  directories:
    - $HOME/.buildroot-dl
    - $HOME/.buildroot-ccache

script:
    - mkdir -p $HOME/.buildroot-dl
    - ln -s $HOME/.buildroot-dl buildroot/dl
    - make FORCE_CCACHE=1 configure-buildroot
    - make build-buildroot -s

deploy:
    provider: script
    script: ./.travis.sh
    skip_cleanup: true
    on:
        branch: master
