sudo: false

addons:
  apt:
    packages:
    - bc

env:
  global:
    - GOPATH: $HOME/gopath
    - GZIP: --rsyncable
    - PATH: $GOPATH/bin:$PATH

cache:
  directories:
    - $HOME/.buildroot-dl
    - $HOME/.buildroot-ccache

before_install:
    - eval "$(gimme 1.5.1)"
    - go get github.com/rasky/multigz/cmd/multigz

script:
    - mkdir -p $HOME/.buildroot-dl
    - ln -s $HOME/.buildroot-dl buildroot/dl
    - make FORCE_CCACHE=1 configure-buildroot
    - make build-buildroot -s
    - multigz --force --best --rsyncable buildroot/output/images/rootfs.tar

deploy:
    provider: script
    script: ./.travis.sh
    skip_cleanup: true
    on:
        branch: master
