#!/bin/sh

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=none

# or set your networking parameters here
eth0.ipaddr=192.168.7.1
eth0.netmask=255.255.255.0
eth0.serverip=192.168.7.11
#eth0.gateway=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=nand
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=nand
# can be either 'nfs', 'tftp', 'nand' or empty
oftree_loc=nand

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
ubiroot=rootfs
rootfsimage=${ubiroot}.${rootfs_type}

# The image type of the kernel. Can be uimage, zimage, raw, or raw_lzo
kernelimage=zImage

# The device tree image to pass the kernel
oftreeimage=at91-sama5d4_xplained.dtb

nand_device=atmel_nand
nand_parts="256k(at91bootstrap),512k(barebox)ro,256k(bareboxenv),256k(bareboxenv2),256k(spare),512k(oftree),6M(kernel),-(rootfs)"
rootfs_mtdblock_nand=7

m25p80_parts="64k(bootstrap),384k(barebox),256k(bareboxenv),256k(bareboxenv2),128k(oftree),-(updater)"

autoboot_timeout=3

bootargs="console=ttyS0,115200 earlyprintk printk.time=1"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m\n# "
